
CAS_SERVER = 'CAS_SERVER'

CAS_USERNAME = 'CAS_USERNAME'
CAS_ATTRIBUTES = 'CAS_ATTRIBUTES'
CAS_SERVICE_TICKET = 'CAS_SERVICE_TICKET'
CAS_PGTIOU = 'CAS_PGTIOU'

CAS_LOGIN_ROUTE = 'CAS_LOGIN_ROUTE'
CAS_LOGOUT_ROUTE = 'CAS_LOGOUT_ROUTE'
CAS_PROXY_ROUTE = 'CAS_PROXY_ROUTE'
CAS_SERVICE_VALIDATE_ROUTE = 'CAS_SERVICE_VALIDATE_ROUTE'
CAS_PROXY_VALIDATE_ROUTE = 'CAS_PROXY_VALIDATE_ROUTE'
CAS_PROXY_CALLBACK_ROUTE = 'CAS_PROXY_CALLBACK_ROUTE'

CAS_AFTER_LOGIN = 'CAS_AFTER_LOGIN'
CAS_AFTER_LOGOUT = 'CAS_AFTER_LOGOUT'

CAS_AFTER_LOGIN_SESSION_URL = 'CAS_AFTER_LOGIN_SESSION_URL'
